### ISSUE TITLE
Sharp modules is being excluded always

### ISSUE THREAD

**Issue by imewish** [AnomalyInnovations/serverless-bundle#103]
Hello,

I have an image processing project which uses sharp, jimp and pg module. I'm trying the serverless-bundle module for the first time.  Providing the sls config below.

```
service: process-images
frameworkVersion: ">=1.13.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

plugins:
  - serverless-pseudo-parameters
  - serverless-step-functions
  - serverless-bundle
package:
  individually: true
  
custom:
  bundle:
    includeModules: true
    sourcemaps: true                
    caching: true                   
    stats: false                    
    linting: false
    forceInclude:
      - sharp
      - jimp  
    ignorePackages:                
      - pg-native                       
    packagerOptions:
      scripts:
        - rm -rf node_modules/sharp && npm install --arch=x64 --platform=linux --target=10.15.0 sharp

```

When I deploy I can see the sharp is excluded from packaging automatically.  

```
Serverless: Bundling with Webpack...
Serverless: Excluding external modules: sharp@^0.22.1, aws-sdk@^2.595.0
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: jimp@^0.12.1
```

Which results in ` "Error: Cannot find module 'sharp'\nRequire stack:\` error.

Am i missing anything in the config?  I tried adding sharp in
