### ISSUE TITLE
run eslint  without ``sls package`` or ``sls deploy``

### ISSUE THREAD

**Issue by chanthafef** [AnomalyInnovations/serverless-bundle#118]
I was wondering about how you include eslint in your worklow.

Do you only make it run on ``sls deploy`` or do you run ``sls package`` before every commit ?

On my local machine, I would like to have the option to :
- run the linter with [husky](https://github.com/typicode/husky) (using githooks) on pre-commit (which works perfectly fine with ``sls package`` - even tho it's slow)
- use the [``--fix`` flag](https://eslint.org/docs/user-guide/command-line-interface#fix) instead of having to fix them manually.

The only option I could think of was to bypass webpack entirely.

```
npm install -g eslint
// and then
eslint "**/*.js" --ignore-pattern node_modules/ -c node_modules/serverless-bundle/src/eslintrc.json --fix
```

Which works (sort of) but then made me realize ``sls deploy`` doesn't lint our test files (jest).

I'll open an other issue and submit a PR about this if that's ok with you.

Note that running eslint this way: 
- fails faster than using ``sls package``
- is easier to read as our terminal doesn't display webpack tracing

Additionaly, in my CI (since I am deploying to multiple stages/accounts) :

1. I still let ``sls deploy`` run the linter in the first stage (say STAGE) 
2. and then disbale it for subsequent stages (say PROD).

```
custom:
  stage: ${opt:stage, self:provider.stage}
  linting:
    dev: true
    stage: true
    prod: false
  bundle:
    linting: ${self:custom.linting.${self:custom.stage}, self.linting.dev}
```
(I will consider setting ``linting: false`` and using the ``èslint`` command mentionned above in my CI if my pipeline ever gets too slow)

Does that look right to you ? or am I missing something ?
