### ISSUE TITLE
Module parse failed: Unexpected character '�' (1:0)

### ISSUE THREAD

**Issue by compwright** [AnomalyInnovations/serverless-bundle#12]
While packaging code that includes [sharp](https://www.npmjs.com/package/sharp) `^0.22.1`, I encountered this error:

```
ERROR in [redacted]/node_modules/sharp/build/Release/sharp.node 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ [redacted]/node_modules/sharp/lib/input.js 5:14-52
 @ [redacted]/node_modules/sharp/lib/index.js
 @ [redacted]
```

**Comment by jayair** [comment]
I wonder if this module is trying to load a file (https://github.com/webpack-contrib/sass-loader/issues/522). Have you used this previously with Webpack?

Also, if you could a package.json + handler file with this import that I can test with? I'll have a look.

**Comment by compwright** [comment]
@jayair here's a test case for you: https://gist.github.com/compwright/6908a7524cbe37e5e388ac1a8706aa9c

Interestingly enough, I can't reproduce it with `sharp@0.23.0`.

**Comment by compwright** [comment]
Related: https://github.com/lovell/sharp/issues/1177

**Comment by jayair** [comment]
Thank you for this. So I played around with it. This needs a special config as noted in that https://github.com/lovell/sharp/issues/1177 issue. Have you used this module with Webpack before?

I don't know if we are going to support this in serverless-bundle. I'm not entirely sure yet. But if you want to use it with serverless-webpack, you need to add it to the externals in the `webpack.config.js`.

``` js
externals: ["sharp", "aws-sdk"],
```

And in serverless-webpack we need to turn on:

``` yml
custom:
  webpack:
    includeModules: true # enable auto-packing of external modules
```

**Comment by compwright** [comment]
Yes, I am currently using it with serverless-webpack.

**Serverless.yml:**

```yaml
plugins:
  - serverless-webpack

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
    packagerOptions:
      scripts:
        - rm -rf node_modules/sharp && npm install --arch=x64 --platform=linux --target=8.10.0 sharp

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - tests/**
    - .env
```

**webpack.config.js:**

```javascript
const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  target: 'node',
  entry: slsw.lib.entries,
  mode: 'development', // slsw.lib.webpack.isLocal ? 'development' : 'production',
  stats: 'minimal',
  externals: [nodeExternals()]
};
```

**Comment by jayair** [comment]
Ah. Yeah I'm not entirely sure what the best way to handle this is. It would be good if we can automatically handle this for users without them having to change the config. Any ideas?

**Comment by compwright** [comment]
Seems like an `externals` configuration option that could be passed through to the underlying webpack would do the trick.

**Comment by Susan123456789** [comment]
Any word on this?  I am also trying to use sharp with the serverless-bundle.  Thanks

**Comment by jayair** [comment]
Yup I'm going to look at it this weekend to figure out a fix.

**Comment by jayair** [comment]
@compwright @Susan123456789 I've added a fix. I've created a beta version for you to test. Install it using:

``` bash
$ npm install --save-dev serverless-bundle@beta
```

I'm excluding the `sharp` package by default. However, I'm not sure about this option that you are using:

``` yml
    packagerOptions:
      scripts:
        - rm -rf node_modules/sharp && npm install --arch=x64 --platform=linux --target=8.10.0 sharp
```

Can you tell me what this does and if you need the plugin to have this option?
