### ISSUE TITLE
Linting not running

### ISSUE THREAD

**Issue by VED-StuartMorris** [AnomalyInnovations/serverless-bundle#132]
Wondering if anyone can point me in the right direction here.

I have the latest version of serverless-bundle installed, we have the linting flag set to true:
```
  bundle:
    sourcemaps: false
    stats: true
    linting: true
    fixPackages: # Include fixes for specific packages
      - 'formidable@1.x'
```

However, linting is not running when running ```sls deploy``` or ```sls package```.

There are forced errors in place, we can check by running ```npm run lint``` which runs a lint task with eslint.

Any reason why the linting would not run? I have run in ```--verbose``` but there is no mention of lint.

Thanks
