### ISSUE TITLE
Middy Validator Integration - necessary force include ajv-i18n package

### ISSUE THREAD

**Issue by renanwilliam** [AnomalyInnovations/serverless-bundle#134]
Hi,

The package https://github.com/middyjs/middy/tree/master/packages/validator has made a recent release that broke projects running with serverless-bundle package. The validator package has some libraries in their dependencies but for some reason ins't resolving. It's throwing the error `Error: Cannot find module 'ajv-keywords`.

It's necessary add the forceInclue the ajv-keywords package
```
custom:
  bundle:
    sourcemaps: false
    caching: false
    linting: false
    forceInclude:
      - pg
      - ajv-keywords
      - ajv-i18n
      - ajv-errors
```

CC https://github.com/middyjs/middy/pull/552
