### ISSUE TITLE
`yarn test` issues with Nested Services Docs

### ISSUE THREAD

**Issue by zlanich** [AnomalyInnovations/serverless-bundle#137]
Hey there! I'm using Yarn Workspaces, and I'm having issues only with using the docs example to run services tests from a parent dir above the individual service dirs, just like example explained in the "Nested Services" section in the docs. Here's a rundown of what I have:
```
<project root>
  - services
     - example-service
        // Almost 100% 1:1 of the serverless bundle install from the docs, just a couple tsconfig tweaks, etc
        - package.json
        - serverless.yml
        - tsconfig.json
  - package.json // Mostly for common dev dependencies
  - tsconfig.json // Base to inherit from
```
I can run commands from within the `example-service` dir just fine (specifically the `yarn test` one, but running `yarn test` from the parent dir (2 dirs up) results in the following error(s):
```
Unknown option: .cloneInputAst. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.

      at throwUnknownError (../../node_modules/babel-jest/node_modules/@babel/core/lib/config/validation/options.js:123:27)
          at Array.forEach (<anonymous>)
          at loadPrivatePartialConfig.next (<anonymous>)
      at evaluateSync (../../node_modules/gensync/index.js:244:28)
```
Here are some of my core files to help:
`<project root>/package.json`:
```json
{
  "name": "boilerplate-serverless",
  "version": "1.0.0",
  "main": "index.js",
  "private": true,
  "devDependencies": {
    "@types/aws-lambda": "^8.10.62",
    "serverless-bundle": "2.0.0",
    "serverless-dotenv-plugin": "^2.1.1",
    "serverless-offline": "^5.3.3",
    "serverless-plugin-monorepo": "^0.9.0"
  },
  "dependencies": {},
  "scripts": {
    "test": "serverless-bundle test"
  }
}

```
`<project root>/tsconfig.json`:
```json
{
    "include": ["./services/**/handler.ts"],
    "compilerOptions": {
        "baseUrl": ".",
        "module": "esnext",
        "lib": ["dom", "esnext", "es2019", "es2020.bigint", "es2020.string", "es2020.symbol.wellknown"],
        "importHelpers": true,
        "declaration": true,
        "sourceMap": true,
        "strict": true,
        "moduleResolution": "node",
        "esModuleInterop": true,
        "skipLibCheck": true,
        "target": "es2019",
        "preserveConstEnums": true,
        "allowJs": true,
        "resolveJsonModule": true,
        "forceConsistentCasingInFileNames": true,
        "pretty": true,
        "noImplicitAny": true,
        "strictNullChecks": true,
        "strictFunctionTypes": true,
        "strictPropertyInitialization": true,
        "noImplicitThis": true,
        "alwaysStrict": true,
        "stripInternal": true,
        "noUnusedLocals": false,
        "noUnusedParameters": false,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "emitDecoratorMetadata": false,
        "experimentalDecorators": false,
        "allowSyntheticDefaultImports": true,
    }
  }
```
`<project root>/services/example-service/package.json`:
```json
{
  "name": "example-service",
  "version": "2.2.0",
  "main": "handler.js",
  "scripts": {
    "test": "yarn --cwd ./../../ test example-service"
  },
  "devDependencies": {
    "@types/aws-lambda": "^8.10.62",
    "serverless-bundle": "2.0.0",
    "serverless-dotenv-plugin": "^2.1.1",
    "serverless-offline": "^5.3.3",
    "serverless-plugin-monorepo": "^0.9.0"
  },
  "dependencies": {}
  }
}

```
`<project root>/services/example-service/serverless.yml`:
```yml
service: example-service

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-monorepo

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

custom:
  bundle:
    packager: yarn
    tsConfig: './tsconfig.json'

```
`<project root>/services/example-service/tsconfig.json`:
```json
{
    "extends": "../../tsconfig.json"
} 
```

Does anyone have any insight on this issue? I've searched high/low for clues, to no avail :(.
