### ISSUE TITLE
NODE_ENV being replace by wrong value

### ISSUE THREAD

**Issue by willfarrell** [AnomalyInnovations/serverless-bundle#139]
When `NODE_ENV` environment variable is set to `development` in the serverless config, the bundled lambda export replaces `process.env.NODE_ENV` with `production`. This is unexpected, I would expect it to be set to `development`. I wasn't able to find anything in the docs coving this. Is there a way to force it to use the value in the serverless config or disable `process.env` replacement?

severless.yml:
```yml
...
plugins:
  - serverless-bundle
...
custom:
  bundle:
    sourcemaps: false
    caching: false
    linting: false
...
provider:
  environment:  # Include dotenv above
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_ENV: ${opt:environment} # run as `development`
...

```
lambda.js
```js
...
const env = process.env.NODE_ENV // replaced with `production` instead of `development`
```

**Comment by jayair** [comment]
Bundle doesn't touch the `NODE_ENV`. I tested it in our base setup and didn't see what you are saying. Can you create a git repo to reproduce this?

**Comment by turakvlad** [comment]
Hey, I have the same issue. My `process.env.NODE_ENV` is changed to `production` at compile time. I think it is related to https://github.com/webpack/webpack/issues/7470. So, even though I have another value as my `NODE_ENV` in my Lambda function's environment variable, it won't help me much, because the compiled code stores a string `production` and not a reference to `process.env.NODE_ENV`. 

We should use this to disable `NODE_ENV` optimization:

```
optimization: {
  nodeEnv: false
}
```

Is there any way to pass this configuration to `serverless-webpack` directly from your plugin?

My config is:

```
  bundle:
    sourcemaps: false
    caching: false
    stats: false
    linting: false
    ignorePackages:
      - pg-native
    forceExclude:
      - aws-sdk
      - chrome-aws-lambda
    copyFiles:
      - from: 'shared/email-templates/*'
        to: './'
    packager: npm
```

In my code I have:

```
console.log(process.env.NODE_ENV)
```

In the compiled code I see:

<img width="863" alt="Screenshot 2020-11-01 at 14 30 01" src="https://user-images.githubusercontent.com/7996184/97804230-272e2480-1c57-11eb-91f0-e9e4dba30577.png">

I expect to see:

```
console.log(process.env.NODE_ENV);
```

Thank you for any help, @jayair.
