### ISSUE TITLE
copyFiles causing error: ERROR in unable to locate...

### ISSUE THREAD

**Issue by stewarthull7** [AnomalyInnovations/serverless-bundle#154]
I have been using serverless-bundle for a while now without any issues. Suddenly, when removing my node_modules folder and running ```npm install```, I am now getting an error. Please see my output below when running serverless offline. I get the same error when running ```serverless deploy```.

```
Serverless: Invoke offline
Serverless: Invoke webpack:validate
Serverless: Using configuration:
{
  "packager": "npm",
  "packagerOptions": {},
  "webpackConfig": "node_modules\\serverless-bundle/src/webpack.config.js",
  "includeModules": {
    "forceExclude": [
      "aws-sdk"
    ],
    "forceInclude": null,
    "packagePath": "package.json"
  },
  "keepOutputDirectory": false
}
Serverless: Removing C:\Users\Stewart\Desktop\Crux Projects Local\Achievement Awards Group\BountiXP Platform\serverless-api\billing\services\billing-address-api\.webpack
Serverless: Bundling with Webpack...
Serverless: Webpack watch invoke: HASH NEW=cf04d716104492eaef2a CUR=null

LOG from copy-webpack-plugin
<e> unable to locate "C:\Users\Stewart\Desktop\Crux Projects Local\Achievement Awards Group\BountiXP Platform\serverless-api\billing\services\billing-address-api\sql\*" at "C:\Users\Stewart\Desktop\Crux Projects Local\Achievement Awards Group\BountiXP Platform\serverless-api\billing\services\billing-address-api\sql\*"
+ 7 hidden lines

ERROR in unable to locate "C:\Users\Stewart\Desktop\Crux Projects Local\Achievement Awards Group\BountiXP Platform\serverless-api\billing\services\billing-address-api\sql\*" at "C:\Users\Stewart\Desktop\Crux Projects Local\Achievement Awards Group\BountiXP Platform\serverless-api\billing\services\billing-address-api\sql\*"
```

Here is my package.json:

```
{
  "name": "billing-address-api",
  "version": "0.1.0",
  "description": "bountixp billing-address api",
  "main": "handler.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "bountixp",
  "license": "ISC",
  "devDependencies": {
    "serverless-bundle": "^3.2.1",
    "serverless-offline": "^6.8.0"
  }
}
```

Here is my serverless.yml:

```
service: billing-address-api

plugins:
  - serverless-bundle
  - serverless-offline

custom:
  bundle:
    linting: false
    copyFiles:                      # Copy any additional files to the generated package
      - from: 'sql/*'
        to: './'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  runtime: nodejs12.x

functions:
...
```

I have tried downgrading to v3.0.0. I've tried removing my package-lock.json file. No changes have been made to my config since it was previously working, only the ```npm install```, so my thoughts are it must be a dependency package issue of some sort. The issue is only on Windows: **Windows 10 Version 1903 (OS Build 18362.1139)**. Works fine on Ubuntu. Issue can be replicated on my developer's PC too.
