### ISSUE TITLE
How to forceExclude git+ssh style dependency

### ISSUE THREAD

**Issue by henhal** [AnomalyInnovations/serverless-bundle#161]
I have a private NPM module sourced through a git+ssh URL, such as

```
"dependencies": {
  "my-lib": "git+ssh://git@github.com:foo/my-lib.git#semver:^2.1"
}
```

I already have a Lambda Layer for this dependency, so I'd like to exclude it from webpacking. However, I cannot get exclusions to work for these kinds of dependencies?

I tried:

```
custom:
  bundle:
    forceExclude:
      - my-lib
      - my-lib.git
      - foo/my-lib
      - foo/my-lib.git
      - git+ssh://git@github.com:foo/my-lib
      - git+ssh://git@github.com:foo/my-lib.git
```
None of these make any difference - the module is bundled anyway. Excluding other normal NPM dependencies work just fine so there's nothing wrong with my setup per se AFAIK.

Furthermore, making this depedendy part of `devDependencies` will _still_ bundle it. The only way I've managed to get rid of this module from the bundle (in favour of the layer) is to not depend on it at all and instead set up a `tsconfig.json` path to a location on disk where this module exists, and if running locally by using `NODE_PATH` such as `NODE_PATH=../layers/my-lib-layer/nodejs/node_modules`. Is there a syntax to reference such module or is it just not possible? The fact that they are included even when listed under `devDependencies` make me suspect this is an error deeper down in the SLS framework itself perhaps?
