### ISSUE TITLE
serverless bundle breaks nestjs configuration

### ISSUE THREAD

**Issue by softmarshmallow** [AnomalyInnovations/serverless-bundle#177]
create boiler plate nestjs project. from serverless-examples/with-typescript-nestjs

run it as is -> works well

remove all plugins and replace it with `serverless-bundle`

Not that it does not compiles, it throws wierd error.

```
[ExceptionHandler] Nest cannot create the module instance. Often, this is because of a circular dependency between modules. Use forwardRef() to avoid it.

(Read more: https://docs.nestjs.com/fundamentals/circular-dependency)
Scope []
   +294ms
Error: Nest cannot create the module instance. Often, this is because of a circular dependency between modules. Use forwardRef() to avoid it.

(Read more: https://docs.nestjs.com/fundamentals/circular-dependency)
Scope []
  
    at NestContainer.addModule (/Users//Documents/GitHub/services/g11n-service/.webpack/service/src/webpack:/Users//Documents/GitHub/services/node_modules/@nestjs/core/injector/container.js:45:1)
    at DependenciesScanner.insertModule (/Users//Documents/GitHub/services/g11n-service/.webpack/service/src/webpack:/Users//Documents/GitHub/services/node_modules/@nestjs/core/scanner.js:61:1)
    at DependenciesScanner.scanForModules (/Users//Documents/GitHub/services/g11n-service/.webpack/service/src/webpack:/Users//Documents/GitHub/services/node_modules/@nestjs/core/scanner.js:31:1)
    at DependenciesScanner.scan (/Users//Documents/GitHub/services/g11n-service/.webpack/service/src/webpack:/Users//Documents/GitHub/services/node_modules/@nestjs/core/scanner.js:25:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at /Users//Documents/GitHub/services/g11n-service/.webpack/service/src/webpack:/Users//Documents/GitHub/services/node_modules/@nestjs/core/nest-factory.js:89:1
    at Function.asyncRun (/Users//Documents/GitHub/services/g11n-service/.webpack/service/src/webpack:/Users//Documents/GitHub/services/node_modules/@nestjs/core/errors/exceptions-zone.js:18:1)
    at NestFactoryStatic.initialize (/Users//Documents/GitHub/services/g11n-service/.webpack/service/src/webpack:/Users//Documents/GitHub/services/node_modules/@nestjs/core/nest-factory.js:88:1)
    at NestFactoryStatic.create (/Users//Documents/GitHub/services/g11n-service/.webpack/service/src/webpack:/Users//Documents/GitHub/services/node_modules/@nestjs/core/nest-factory.js:34:1)
 ✘@-MacBook-Pro  ~/Documents/GitHub/services/g11n-service   service/g11n ●  (node:56887) UnhandledPromiseRejectionWarning: RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 56887.
    at /Users//Documents/GitHub/services/node_modules/serverless-bundle/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:56887) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:56887) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jayair** [comment]
I've heard of some other folks having issues with Nestjs. Do you know if we can use Webpack with it?

**Comment by softmarshmallow** [comment]
'Cause there are lots of examples using nestjs with webback on nestjs's official example and serverless-examples.

It's odd that it breaks. (on run time.)

**Comment by softmarshmallow** [comment]
@jayair it's pretty easy to reproduce. are you planning to support nestjs?

**Comment by Nightbr** [comment]
Hey, I achieved to make a nestjs app working with serverless with this config:

```
package:
  individually: true
custom:
  bundle:
    sourcemaps: true
    tsConfig: 'tsconfig.app.json'
    linting: true
    packager: yarn
    forceInclude:
      - '@slynova/flydrive-s3'
    ignorePackages:
      - pg-native
      - nats
      - mqtt
      - kafkajs
      - grpc
      - apollo-server-express
      - apollo-server-fastify
      - class-transformer/storage
      - cache-manager
      - '@nestjs/websockets/socket-module'
    forceExclude:
      - aws-sdk
    externals:
      - argon2 # https://github.com/serverless-heaven/serverless-webpack/issues/659
```

It's working on local invoke but failed on AWS Lambda, no error, just some weird timeout... Try to increase the timeout (to 2min) but still stuck during the bootstrap of nestjs. 

I think it's because it bundles it bit too much, Nestjs recommand to not bundle in one file but only compile the code & create a minimal package.json with dependencies. Seems a good way to work with layer, add all dependencies to a layer & compile only the lambda code.

Happy to talk with someone who struggles on this to find a solution and share it with others :ok_hand:
