### ISSUE TITLE
Webpack failing; trying to use bcrypto binaries

### ISSUE THREAD

**Issue by msharkeyiii** [AnomalyInnovations/serverless-bundle#199]
I'm trying to use an NPM package that depends on a library called `bcrypto` in my project; NodeJS 14 AWS Lambda.

bcrypto uses binaries that are located in: `node_modules/bcrypto/build/Release/bcrypto.node` among others.

Webpack is completely failing to include any of these binaries, no matter what config I've tried so far.

The closest I got was invoking the lambda locally via: `serverless invoke local --function hello-world` it complained that the binary was not found in my `~/.serverless/bin` folder. So when I copied all the binaries there, it's working now locally.

When I try adding: `externals: all`, or `externals: bcrypto`, and do `serverless deploy` it says:
`Packing external modules`, but then fails silently, with no error.

I've been stuck on this for 2 days now. Any help would be very much appreciated! How do I upload these binaries to the lambda so they can be referenced at runtime?

Here's my serverless.yml

```
service: my-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-bundle

package:
  individually: true
  include:
    - bin/*

functions:
  hello-world:
    handler: handler.hello

custom:
  bundle:
    includeModules: true
    sourcemaps: false
    caching: false
```

and here is the lambda output error:

```
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'bcrypto.node'",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'bcrypto.node'",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
    "    at Module.load (internal/modules/cjs/loader.js:863:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
    "    at internal/main/run_main_module.js:17:47"
  ]
}
```
