### ISSUE TITLE
Using Lambda Layer for npm package

### ISSUE THREAD

**Issue by imthatcarlos** [AnomalyInnovations/serverless-bundle#23]
I want to use an npm package as a lambda layer, so I've set up my serverless.yml file like so
```yml
package:
  individually: true
layers:
  tupelo-wasm-sdk:
    path: serverless
    name: tupelo-wasm-sdk
    compatibleRuntimes:
      - nodejs10.x
process_scooter_status:
    timeout: 420
    handler: serverless/process_scooter_status.handler
    layers:
      - { Ref: TupeloDashwasmDashsdkLambdaLayer }
```

and after reading [this post](https://medium.com/the-apps-team/how-to-add-nodejs-library-dependencies-in-a-aws-lambda-layer-with-serverless-framework-d774cb867197) I've got my project directory set up like this
```
serverless/
| nodejs/node_modules/tupelo-wasm-sdk/
| process_scooter_status.js
```

In my case, I've modified the code in `nodejs/node_modules/tupelo-wasm-sdk/` so it's different from the actual npm reference. 

So when I run `serverless package` I see that the layer is packaged properly, but the final source code in `.serverless` for the function shows the npm library code from the npm package, **not the modified code I specified to be included as the lambda layer**. 

I feel like either
- there should be some config to let this plugin know that we are using a lambda layer as an npm package, and to pull source code from here .... 
- OR I need to specify not to include this package as part of the transpiled js function code

**Comment by imthatcarlos** [comment]
Forgot to include that the `tupelo-wasm-sdk` npm is set as a **dev dependency**

**Comment by jayair** [comment]
Hmm I hadn't really considered Layers as a part of this process. But do you know how you would handle this issue if you were using serverless-webpack directly?

**Comment by nagey** [comment]
With `serverless-webpack` you can configure it like so:
```
custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
        - chrome-aws-lambda
```

where `chrome-aws-lambda` comes from your layer
