### ISSUE TITLE
Module not getting added to externals on deploy

### ISSUE THREAD

**Issue by hdwatts** [AnomalyInnovations/serverless-bundle#279]
From my `serverless.yml`:

Using: `serverless-bundle@5.0.1`

```
custom:
  bundle:
    linting: false
    ignorePackages:
      - pg-native
      - canvas
    externals:
      - envkey
      - pdfjs-dist
```

`envkey` is correctly getting added to the deployed `node_modules` folder - however `pdfjs-dist` does not. Are there certain requirements that must be met for it to work? I noticed it still isn't included even if I use `all`.

**Comment by hdwatts** [comment]
Solved via adding the fully qualified  module I'm actually importing: `pdfjs-dist/legacy/build/pdf`

```
custom:
  bundle:
    linting: false
    ignorePackages:
      - pg-native
      - canvas
    externals:
      - envkey
      - 'pdfjs-dist/legacy/build/pdf'
```
