### ISSUE TITLE
TypeError: require is not a function

### ISSUE THREAD

**Issue by thiagoneves** [AnomalyInnovations/serverless-bundle#28]
Hi guys, 

I'm trying to use serverless-bundle in my project but i got the error below when added an external module.

***TypeError: require is not a function***

package.json
```
{
  "name": "serverless-bundle-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "jest"
  },
  "license": "ISC",
  "devDependencies": {
    "aws-sdk": "^2.487.0",
    "serverless-bundle": "^1.2.5",
    "serverless-offline": "^5.11.0"
  },
  "dependencies": {
    "wpapi": "^1.2.1"
  }
}
```

serverless.yml
```
service: serverless-bundle-test

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs10.x
  stage: dev

functions:

  featured:
    handler: src/handlers/handler.main
    events:
      - http:
         path: /my-path
         method: get
         cors: true
```

handler.js
```
import WPAPI from 'wpapi';

module.exports.hello = async event => {
  
  const wpapi = new WPAPI({ endpoint: '' });
  console.log(wpapi);

  return {
    statusCode: 200,
    body: JSON.stringify(
      {
        message: 'Go Serverless v1.0! Your function executed successfully!',
        input: event,
      },
      null,
      2,
    ),
};

```
