### ISSUE TITLE
unneeded files cannot be excluded

### ISSUE THREAD

**Issue by pkit** [AnomalyInnovations/serverless-bundle#283]
I want to exclude `migrations/**` from bundling (tried all the possible combinations: `migrations` , `migrations/**`, `migrations/**/*` , `migrations/**/*.ts`, `migrations/*.ts`.
```yaml
package:
  individually: true
  exclude:
    - migrations/**/*
custom:
  bundle:
    excludeFiles: "migrations/**/*"
```
It's not possible right now as it will fail miserably by still trying to lint and webpack it.
