### ISSUE TITLE
Error importAssertions

### ISSUE THREAD

**Issue by robertocerdasilva** [AnomalyInnovations/serverless-bundle#316]
Hello good day.

I have an API that uses json files on some endpoints.
I am using NODE 16 and when starting the application on local server, the console requires me to use `assert { type: 'json' }` when importing json files:

` import FILE from 'file.json' assert { type: 'json' } `

When executing   `serverless deploy`  the console shows the following error:

Support for the experimental syntax 'importAssertions' isn't currently enabled

Helpme plis :( thanks

serverless.yml
```
plugins:
    - serverless-bundle
    
custom:
    bundle:
        sourcemaps: false
        linting: false
        ignorePackages:
            - pg-native
```
