### ISSUE TITLE
forceExclude not working

### ISSUE THREAD

**Issue by hugobcar** [AnomalyInnovations/serverless-bundle#356]
Hi.

I'm using `serverless:6.0.0` and I'm having some problems with `forceExclude: ["aws-sdk"]`. Below is a part of `serverless.yml` configuration:
```yaml
custom:
  bundle:
    # stats: true #enable this to see webpack output
    stats: false
    caching: true
    packager: yarn
    forceExclude: ["aws-sdk"]
    excludeFiles: "node_modules/aws-sdk/**"
    copyFiles: # Copy any additional files to the generated package
      - from: "src/modules/aws/chime/index.html" # Where the files are currently
        to: "./src"
      - from: "src/modules/amwell/wsdl/" # Where the files are currently
        to: "./src"
    packagerOptions:
      scripts:
        - rm -rf node_modules/aws-sdk
```

I'm performing serverless using `CodeBuild` on AWS.

![image](https://user-images.githubusercontent.com/10134807/230481820-fddddc3d-b41e-4340-b7f7-8a31a4b30c9a.png)

Above you can see the message `Excluding external modules: aws-sdk@2.1149.0` in one build, but in some case the build doesn't show this message and I think the `forceExclude` not working.

**Note:** The both logs are using the same commit! Sometimes it works and sometimes it doesn't work.

Any ideas?
