### ISSUE TITLE
When using esbuild and sourcemaps, any resulting error messages do not utilize the sourcemap.

### ISSUE THREAD

**Issue by doulighan** [AnomalyInnovations/serverless-bundle#370]
```
serverless-bundle: 6.1.0
node: 16, 17, 18

bundle:
    linting: false
    esbuild: true
    caching: true
    sourcemaps: true
```

The sourcemap files are generated under .webpack, but error messages still reference the transpiled code directly. This happens both deployed on AWS, and for `serverless invoke local`

Switching to `esbuild: false` fixes the sourcemaps in both situations, but its certainly slower.
