### ISSUE TITLE
After adding serverless bundle it deploys successfully but Api calls shows 502 error after using serverless bundle 

### ISSUE THREAD

**Issue by karunakapil** [AnomalyInnovations/serverless-bundle#52]

**Comment by jayair** [comment]
Can you share some details on the actual error you are getting?

**Comment by elhe26** [comment]
I'm getting the same error.

This is the log:

{
    "errorType": "TypeError",
    "errorMessage": "Cannot set property 'handler' of undefined",
    "stack": [
        "TypeError: Cannot set property 'handler' of undefined",
        "    at Module.<anonymous> (/var/task/src/handlers/webpack:/D:/prj/auction-service-nodejs/src/handlers/createAuction.js:48:1)",
        "    at Module.<anonymous> (/var/task/src/handlers/createAuction.js:5777:30)",
        "    at __webpack_require__ (/var/task/src/handlers/webpack:/webpack/bootstrap:19:1)",
        "    at /var/task/src/handlers/webpack:/webpack/bootstrap:83:1",
        "    at Object.<anonymous> (/var/task/src/handlers/createAuction.js:87:10)",
        "    at Module._compile (internal/modules/cjs/loader.js:1133:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)",
        "    at Module.load (internal/modules/cjs/loader.js:977:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:877:14)",
        "    at Module.require (internal/modules/cjs/loader.js:1019:19)"
    ]
}

**Comment by jayair** [comment]
Can you share what your serverless.yml and handler file looks like?

**Comment by JamesForan** [comment]
I am also getting this error.

Have been using serverless for a while, and just testing serverless-bundle for the first time...

serverless.yml
```yaml
service: isott

package:
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-bundle # Package our functions with Webpack
custom:
  bundle:
    forceExclude:                   # Don't include these in the package
      - _http_common
provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  apiKeys:
  - isottClient
  - stravaWebhookToken

functions:
  sqsMaster:
    handler: functions/sqsMaster.handler
    events:
      - schedule:
          rate: rate(2 minutes)
          enabled: true
...
```
And the code from sqsMaster.js file  is as follows...  I cannot provide the data from the webpack file, because its too large.

I think the issue may be with how I am creating the function.

```js
const AWS = require('aws-sdk')
// Set the region we will be using
AWS.config.update({ region: 'us-east-1' })
// Create SQS service client
const sqs = new AWS.SQS({ apiVersion: '2012-11-05' })

// eslint-disable-next-line no-undef
const sqsEventUpdate = process.env.EVENTUPDATE_SQS_URL
const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient({
  log: ['warn'],
})
const { headers } = require('utils')
module.exports.handler = async () => {
  try {
    // read data from task table, tasks to be executed in the next 15 minutes.
    // for each task, create a record in the appropriate queue.
    console.log('sqsMaster: started')
    const currTime = new Date().getTime()
    const lte = new Date(currTime + 15 * 60000)
    const tasks = await prisma.task.findMany({
      where: {
        status: 'NEW',
        scheduled: {
          lte,
        },
      },
    })

    console.log(`about to schedule ${tasks.length} tasks`)

    for (let index = 0; index < tasks.length; index++) {
      let task = tasks[index]

      const scheduled = new Date(task.scheduled).getTime()
      const scheduledDelay = (scheduled - currTime) / 1000
      // only delay if scheduled time is in future.
      const DelaySeconds = scheduledDelay > 0 ? Math.round(scheduledDelay) : 0
      const MessageBody = JSON.stringify(task)

      const params = {
        MessageBody,
        DelaySeconds,
        QueueUrl: sqsEventUpdate,
      }

      const data = await sqs.sendMessage(params).promise()
      const updated = await prisma.task.update({
        where: { id: task.id },
        data: { status: 'QUEUED' },
      })
      console.log(data)
      console.log(updated)
    }

    return {
      statusCode: 200,
      headers,
      body: {
        sqsMaster: 'complete',
      },
    }
  } catch (error) {
    // need to clean up the error processes in general.
    console.log(error.message)
    return {
      statusCode: 500,
      headers,
      body: error.name + ': ' + error.message,
    }
  } finally {
    prisma.$disconnect()
  }
}
```

Appreciate your input and help!
